import { Store } from "../viewmodels/Store";

export const zaraStores: Store[] = [
    { name: 'Zara - Paseo de la Castellana', city: 'Madrid', address: 'Paseo de la Castellana 79', country: 'Spain' },
    { name: 'Zara - Plaça de Catalunya', city: 'Barcelona', address: 'Plaça de Catalunya', country: 'Spain' },
    { name: 'Zara - Oxford Street', city: 'London', address: 'Oxford Street', country: 'UK' },
    { name: 'Zara - Regent Street', city: 'London', address: 'Regent Street', country: 'UK' },
    { name: 'Zara - Champs-Élysées', city: 'Paris', address: 'Champs-Élysées', country: 'France' },
    { name: 'Zara - Rue de Rivoli', city: 'Paris', address: 'Rue de Rivoli', country: 'France' },
    { name: 'Zara - Corso Vittorio Emanuele II', city: 'Milan', address: 'Corso Vittorio Emanuele II', country: 'Italy' },
    { name: 'Zara - Via del Corso', city: 'Rome', address: 'Via del Corso', country: 'Italy' },
    { name: 'Zara - Kurfürstendamm', city: 'Berlin', address: 'Kurfürstendamm', country: 'Germany' },
    { name: 'Zara - Neuhauser Strasse', city: 'Munich', address: 'Neuhauser Strasse', country: 'Germany' },
    { name: 'Zara - 5th Avenue', city: 'New York City', address: '5th Avenue', country: 'USA' },
    { name: 'Zara - SoHo', city: 'New York City', address: 'SoHo', country: 'USA' },
    { name: 'Zara - The Grove', city: 'Los Angeles', address: 'The Grove', country: 'USA' },
    { name: 'Zara - Beverly Center', city: 'Los Angeles', address: 'Beverly Center', country: 'USA' },
    { name: 'Zara - Lincoln Road', city: 'Miami', address: 'Lincoln Road', country: 'USA' },
    { name: 'Zara - Toronto Eaton Centre', city: 'Toronto', address: 'Eaton Centre', country: 'Canada' },
    { name: 'Zara - Pacific Centre', city: 'Vancouver', address: 'Pacific Centre', country: 'Canada' },
    { name: 'Zara - Wangfujing', city: 'Beijing', address: 'Wangfujing', country: 'China' },
    { name: 'Zara - Nanjing Road', city: 'Shanghai', address: 'Nanjing Road', country: 'China' },
    { name: 'Zara - Shibuya', city: 'Tokyo', address: 'Shibuya', country: 'Japan' },
    { name: 'Zara - Ginza', city: 'Tokyo', address: 'Ginza', country: 'Japan' },
    { name: 'Zara - Myeongdong', city: 'Seoul', address: 'Myeongdong', country: 'South Korea' },
    { name: 'Zara - Orchard Road', city: 'Singapore', address: 'Orchard Road', country: 'Singapore' },
    { name: 'Zara - The Dubai Mall', city: 'Dubai', address: 'The Dubai Mall', country: 'UAE' },
    { name: 'Zara - Mall of the Emirates', city: 'Dubai', address: 'Mall of the Emirates', country: 'UAE' },
    { name: 'Zara - King of Prussia Mall', city: 'Philadelphia', address: 'King of Prussia Mall', country: 'USA' },
    { name: 'Zara - Plaza Las Américas', city: 'San Juan', address: 'Plaza Las Américas', country: 'Puerto Rico' },
    { name: 'Zara - Centro Comercial Andino', city: 'Bogotá', address: 'Centro Comercial Andino', country: 'Colombia' },
    { name: 'Zara - Shopping Cidade Jardim', city: 'São Paulo', address: 'Shopping Cidade Jardim', country: 'Brazil' },
    { name: 'Zara - Shopping Leblon', city: 'Rio de Janeiro', address: 'Shopping Leblon', country: 'Brazil' },
    { name: 'Zara - Buenos Aires', city: 'Buenos Aires', address: 'Galerías Pacífico', country: 'Argentina' },
    { name: 'Zara - Centro Santa Fe', city: 'Mexico City', address: 'Centro Santa Fe', country: 'Mexico' },
    { name: 'Zara - Polanco', city: 'Mexico City', address: 'Polanco', country: 'Mexico' },
    { name: 'Zara - Sydney CBD', city: 'Sydney', address: 'Pitt Street', country: 'Australia' },
    { name: 'Zara - Melbourne Central', city: 'Melbourne', address: 'Melbourne Central', country: 'Australia' },
    { name: 'Zara - V&A Waterfront', city: 'Cape Town', address: 'V&A Waterfront', country: 'South Africa' },
    { name: 'Zara - Sandton City Mall', city: 'Johannesburg', address: 'Sandton City Mall', country: 'South Africa' },
    { name: 'Zara - King Abdulaziz Road', city: 'Riyadh', address: 'Kingdom Centre', country: 'Saudi Arabia' },
    { name: 'Zara - Cairo Festival City', city: 'Cairo', address: 'Cairo Festival City', country: 'Egypt' },
    { name: 'Zara - Westfield London', city: 'London', address: 'Westfield London', country: 'UK' },
    { name: 'Zara - Stratford City', city: 'London', address: 'Westfield Stratford City', country: 'UK' },
    { name: 'Zara - La Défense', city: 'Paris', address: 'Les Quatre Temps', country: 'France' },
    { name: 'Zara - La Maquinista', city: 'Barcelona', address: 'La Maquinista', country: 'Spain' },
    { name: 'Zara - Serrano', city: 'Madrid', address: 'Calle Serrano', country: 'Spain' },
    { name: 'Zara - Rockefeller Center', city: 'New York City', address: 'Rockefeller Center', country: 'USA' },
    { name: 'Zara - Times Square', city: 'New York City', address: 'Times Square', country: 'USA' },
    { name: 'Zara - Magnificent Mile', city: 'Chicago', address: 'North Michigan Avenue', country: 'USA' },
    { name: 'Zara - South Coast Plaza', city: 'Costa Mesa', address: 'South Coast Plaza', country: 'USA' },
    { name: 'Zara - Union Square', city: 'San Francisco', address: 'Union Square', country: 'USA' },
    { name: 'Zara - Ala Moana Center', city: 'Honolulu', address: 'Ala Moana Center', country: 'USA' },
    { name: 'Zara - Westfield Garden State Plaza', city: 'Paramus', address: 'Westfield Garden State Plaza', country: 'USA' },
    { name: 'Zara - Mall of America', city: 'Bloomington', address: 'Mall of America', country: 'USA' },
    { name: 'Zara - Vancouver Pacific Centre', city: 'Vancouver', address: 'Pacific Centre', country: 'Canada' },
    { name: 'Zara - Yorkdale Shopping Centre', city: 'Toronto', address: 'Yorkdale Shopping Centre', country: 'Canada' },
    { name: 'Zara - Harbour City', city: 'Hong Kong', address: 'Harbour City', country: 'Hong Kong' },
    { name: 'Zara - Times Square', city: 'Hong Kong', address: 'Times Square', country: 'Hong Kong' },
    { name: 'Zara - Marina Bay Sands', city: 'Singapore', address: 'Marina Bay Sands', country: 'Singapore' },
    { name: 'Zara - Siam Paragon', city: 'Bangkok', address: 'Siam Paragon', country: 'Thailand' },
    { name: 'Zara - VivoCity', city: 'Singapore', address: 'VivoCity', country: 'Singapore' },
    { name: 'Zara - KLCC', city: 'Kuala Lumpur', address: 'Suria KLCC', country: 'Malaysia' },
    { name: 'Zara - Istanbul Cevahir', city: 'Istanbul', address: 'Cevahir Mall', country: 'Turkey' },
    { name: 'Zara - İstinyePark', city: 'Istanbul', address: 'İstinyePark', country: 'Turkey' },
    { name: 'Zara - Mall of Africa', city: 'Midrand', address: 'Mall of Africa', country: 'South Africa' },
    { name: 'Zara - Gateway Theatre of Shopping', city: 'Durban', address: 'Gateway Theatre of Shopping', country: 'South Africa' },
    { name: 'Zara - Eastgate Shopping Centre', city: 'Johannesburg', address: 'Eastgate Shopping Centre', country: 'South Africa' },
    { name: 'Zara - City Stars', city: 'Cairo', address: 'City Stars', country: 'Egypt' },
    { name: 'Zara - Mall of Arabia', city: 'Cairo', address: 'Mall of Arabia', country: 'Egypt' },
    { name: 'Zara - Eldorado Mall', city: 'São Paulo', address: 'Eldorado Mall', country: 'Brazil' },
    { name: 'Zara - Iguatemi São Paulo', city: 'São Paulo', address: 'Iguatemi São Paulo', country: 'Brazil' },
    { name: 'Zara - Barra Shopping', city: 'Rio de Janeiro', address: 'Barra Shopping', country: 'Brazil' },
    { name: 'Zara - Colaba Causeway', city: 'Mumbai', address: 'Colaba Causeway', country: 'India' },
    { name: 'Zara - Select Citywalk', city: 'New Delhi', address: 'Select Citywalk', country: 'India' },
    { name: 'Zara - DLF Mall of India', city: 'Noida', address: 'DLF Mall of India', country: 'India' },
    { name: 'Zara - Orion Mall', city: 'Bangalore', address: 'Orion Mall', country: 'India' },
];
  